Update colors script

diff --git a/.scripts/colors b/.scripts/colors
--- a/.scripts/colors
+++ b/.scripts/colors
@@ -1,6 +1,31 @@
 #!/usr/bin/env bash
-colors=("black" "red" "green" "yellow" "blue" "magenta" "cyan" "white" "black" "red" "green" "yellow" "blue" "magenta" "cyan")
-for i in {0..14}; do
-  echo -e "\e[38;5;${i}m color$i ${colors[$i]} \e[0m"
-done
-echo
+case "$1" in
+  set)
+    wp="${2:-$WALLPAPER_PATH}"
+    [[ "$wp" ]] || { echo 'Missing wallpaper path.' && exit 0; }
+    [[ -d "$wp" ]] && wp="$(find "$wp" -type f | shuf -n 1)"
+    wpg -s "$wp"
+    ;;
+
+  reload)
+    i3-msg reload
+    pkill dunst && dunst &
+    besterlockscreen -u -e ''
+    ;;
+
+  show)
+    # Show a list of colors
+    colors=(black red green yellow blue magenta cyan white)
+    for i in {0..15}; do
+      j=$i; (( i > 7 )) && j=$(( i - 8 ))
+      echo -e "color$i: \e[38;5;${i}m${colors[$j]}\e[0m"
+    done
+    ;;
+
+  *)
+    echo "usage: $0 [options]"
+    echo '  options:'
+    echo '    set  -- set wallpaper and generate colorscheme'
+    echo '    show -- show a list of colors'
+    ;;
+esac
